#
# Master makefile for Miner source
#
# Makes all the executable by visiting subdirs and making there
#

CLEAN_TARGS = $(OBJDIR)\*.obj

PROGS = hogfile

HOGFILE_SRCS = hogfile.c 

#rules and targets common to all Miner makefiles
%include $(INIT)\makefile.def
