#
# Master makefile for Miner source
#
# Makes all the executable by visiting subdirs and making there
#

LIBDIR = ..\main
#

CCFLAGS = /dNETWORK /dRELEASE /dNDEBUG

CLEAN_TARGS = $(OBJDIR)\*.obj

INSTALL_TARGS = cfile.lib cfile.h nocfile.h

LIBS = cfile

CFILE_OBJS = cfile.obj

#rules and targets common to all Miner makefiles
%include $(INIT)\makefile.def
